language: R
cache: packages
sudo: false
r: 3.2.3
warnings_are_errors: false
before_install:
  - tlmgr install index
deploy:
  provider: releases
  api_key:
    secure: mLzoMfNmFB+mSkYAviH135BIloTvf51cUbxz++wwOWIqgs9P+z/Z/S7wet9sPNKH3R/QigNVHt9izpD7z2pGN2JGvtx2Tcag5+M/knaOAPM6op7JQwEZvCwnRylTqa8w1uQXtlNd7viQx4Fs09hEPHX/acRUzukvzFxJJ4Pf7Mab8Yd4mLx9PZNd1ZrMKsfkhru4dapPh+U1Rr6O93e2CeIq7aTOuxhnTNJSV3zZzJIbHV7WxRN/Qto6QJkfKJtvoAwllw2EjHJMG+IBFKqQvVF4qkSHe5VDwdIObtYf4yQh0b9Gd4d+gfgm2URtzfJrs3a3V08U+xQZfwl+DuXMVYuRoe2bPjS9dLmHrSGqLi6KDmvwyRphcNJBmsQJIohtc1EOL5q54OTji26GkcGcUJJ/D+/KiMo3YwbWbLOKucjQRvlOCVUDVwHc6yDEVtREjdMKLZl0pkk+4Vkv9K/zYAGu1GOtMVB2i1SxRDiHeNNTeiaOSEdDNG3YnRaOGgAKwhbLMxbmA5DdLgm/C0iaNT0ELYMw9QLxLDveivS9ko2ttH/RMTureutpPr/YBrWWCqS+ASWa5nCXzt31oJ/EYezdWANsyMMO0/JTiqfExIMb7sTX4WXhEoBtUBU0xusOt8GevO2dcxRXyI4gb/G0UXEC3mj6V16jZSodJkRORAI=
  file: ! '*.tar.gz'
  skip_cleanup: true
  on:
    repo: mskyttner/swedishbirdtrends
    tags: true
